# Generated by Django 3.1.5 on 2021-01-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=1000)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(max_length=10000)),
                ('watch_time', models.PositiveIntegerField()),
                ('sound', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=100)),
                ('trailer', models.CharField(max_length=1000)),
                ('year', models.PositiveIntegerField()),
                ('picture', models.FileField(upload_to='')),
            ],
        ),
    ]
