# Generated by Django 3.1.5 on 2021-01-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movievideo',
            field=models.CharField(default=111111111111111111111, max_length=1000),
            preserve_default=False,
        ),
    ]
